### ISSUE TITLE
Setup React App using Vite

### ISSUE THREAD

**Issue by mickeymond** [FavoriteGirl/blog-app#1]

**Comment by mickeymond** [comment]
@FavoriteGirl I can see you have done the issue.
Is that the case?

**Comment by FavoriteGirl** [comment]
Affirmative

**Comment by FavoriteGirl** [comment]
Hi @mickeymond, should i install Tailwind and React Router Dom or wait for it to be issued?

**Comment by mickeymond** [comment]
@FavoriteGirl I am going to assign a new issue to you for that.
